using I18NPortable;

namespace NDB.Covid19.ViewModels
{
    public static class ErrorViewModel
    {
        public static string REGISTER_ERROR_NOMATCH_HEADER => "REGISTER_ERROR_NOMATCH_HEADER".Translate();
        public static string REGISTER_ERROR_NOMATCH_DESCRIPTION => "REGISTER_ERROR_NOMATCH_DESCRIPTION".Translate();
        public static string REGISTER_ERROR_TOOMANYTRIES_HEADER => "REGISTER_ERROR_TOOMANYTRIES_HEADER".Translate();
        public static string REGISTER_ERROR_TOOMANYTRIES_DESCRIPTION => "REGISTER_ERROR_TOOMANYTRIES_DESCRIPTION".Translate();
        public static string REGISTER_ERROR_HEADER => "REGISTER_ERROR_HEADER".Translate();
        public static string REGISTER_ERROR_DESCRIPTION => "REGISTER_ERROR_DESCRIPTION".Translate();
        public static string REGISTER_ERROR_DISMISS => "REGISTER_ERROR_DISMISS".Translate();
        public static string REGISTER_LEAVE_HEADER => "REGISTER_LEAVE_HEADER".Translate();
        public static string REGISTER_LEAVE_DESCRIPTION => "REGISTER_LEAVE_DESCRIPTION".Translate();
        public static string REGISTER_LEAVE_CANCEL => "REGISTER_LEAVE_CANCEL".Translate();
        public static string REGISTER_LEAVE_CONFIRM => "REGISTER_LEAVE_CONFIRM".Translate();
        public static string REGISTER_ERROR_ACCESSIBILITY_CLOSE_BUTTON_TEXT => "REGISTER_ERROR_ACCESSIBILITY_CLOSE_BUTTON_TEXT".Translate();
        public static string REGISTER_ERROR_ACCESSIBILITY_TOOMANYTRIES_HEADER => "REGISTER_ERROR_ACCESSIBILITY_TOOMANYTRIES_HEADER".Translate();
        public static string REGISTER_ERROR_ACCESSIBILITY_TOOMANYTRIES_DESCRIPTION => "REGISTER_ERROR_ACCESSIBILITY_TOOMANYTRIES_DESCRIPTION".Translate();
        public static string REGISTER_ERROR_FETCH_FHI_DATA_HEADER => "REGISTER_ERROR_FETCH_FHI_DATA_HEADER".Translate();
        public static string REGISTER_ERROR_FETCH_FHI_DATA_DESCRIPTION => "REGISTER_ERROR_FETCH_FHI_DATA_DESCRIPTION".Translate();
        public static string REGISTER_CONTINUE_WITH_SELF_TEST_BUTTON_TEXT => "REGISTER_CONTINUE_WITH_SELF_TEST_BUTTON_TEXT".Translate();
        public static string REGISTER_ERROR_NOT16YEARSOLD_HEADER => "REGISTER_ERROR_NOT16YEARSOLD_HEADER".Translate();
        public static string REGISTER_ERROR_NOT16YEARSOLD_DESCRIPTION => "REGISTER_ERROR_NOT16YEARSOLD_DESCRIPTION".Translate();
    }
}
