using I18NPortable;

namespace NDB.Covid19.ViewModels
{
    public class NotificationChannelsViewModel
    {
        public static string NOTIFICATION_CHANNEL_EXPOSURE_NAME => "NOTIFICATION_CHANNEL_EXPOSURE_NAME".Translate();
        public static string NOTIFICATION_CHANNEL_EXPOSURE_DESCRIPTION => "NOTIFICATION_CHANNEL_EXPOSURE_DESCRIPTION".Translate();
        public static string NOTIFICATION_CHANNEL_BACKGROUND_FETCH_NAME => "NOTIFICATION_CHANNEL_BACKGROUND_FETCH_NAME".Translate();
        public static string NOTIFICATION_CHANNEL_BACKGROUND_FETCH_DESCRIPTION => "NOTIFICATION_CHANNEL_BACKGROUND_FETCH_DESCRIPTION".Translate();
        public static string NOTIFICATION_CHANNEL_PERMISSIONS_NAME => "NOTIFICATION_CHANNEL_PERMISSIONS_NAME".Translate();
        public static string NOTIFICATION_CHANNEL_PERMISSIONS_DESCRIPTION => "NOTIFICATION_CHANNEL_PERMISSIONS_DESCRIPTION".Translate();
        public static string NOTIFICATION_CHANNEL_REMINDER_NAME => "NOTIFICATION_CHANNEL_REMINDER_NAME".Translate();
        public static string NOTIFICATION_CHANNEL_REMINDER_DESCRIPTION => "NOTIFICATION_CHANNEL_REMINDER_DESCRIPTION".Translate();
        public static string NOTIFICATION_CHANNEL_COUNTDOWN_NAME => "NOTIFICATION_CHANNEL_COUNTDOWN_NAME".Translate();
        public static string NOTIFICATION_CHANNEL_COUNTDOWN_DESCRIPTION => "NOTIFICATION_CHANNEL_COUNTDOWN_DESCRIPTION".Translate();
    }
}
